import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/presentation/components/Header/Header";
import SideBar from "@/presentation/components/SideBar/SideBar";

const inter = Inter({
  subsets: ["latin"],
  display: "swap", // Melhora o carregamento visual
});

export const metadata: Metadata = {
  title: "GeoStats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${inter.className} h-full antialiased`}>
      <body className="min-h-screen bg-tertiary-50">
        <div className="flex min-h-screen">
          <SideBar />
          <main className="flex flex-1 flex-col">
            <Header />
            <div className="flex-1 overflow-auto p-6">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
